<?php
use Aci\Payment\Block\Widget\CardTypeIcons;

/**
 * @var $block CardTypeIcons
 */
$existingData = $block->getData('images');

if ($existingData) {
    $existingData = json_decode($existingData, true);
} else {
    $existingData= [];
}

/**
 * @var Magento\Framework\Escaper $escaper
 */
?>
<script>
    require(
        ['jquery', 'Magento_Ui/js/modal/confirm'],
        function($, confirmation) {

        $(".delete_img").change(function (event) {

            if ($(this).is(":checked")) {
                let currentElement = $(this);
                confirmation({
                    title: $.mage.__('Do you really want to delete the icon?'),
                    content: $.mage.__('Are you sure you want to delete the icon '+$(this).val()+'?'),
                    actions: {
                        confirm: function(){
                            return true
                        },
                        cancel: function(){
                            $(currentElement).prop('checked', false);
                            return false;
                        },
                        always: function(){}
                    }

                });
            }
        });

        $("#tryzensignite_aci_cc_card_type_icons_image").change(function () {
            let afterContent = $.mage.__('1 File')
            if ($(this)[0].files.length > 1) {
                afterContent = $.mage.__($(this)[0].files.length + ' Files')
            }
            $(".payments__upload-content").html(afterContent);
        })
    });
</script>
<div class="card-payments__logo">
    <div class="field">
        <input
            id="tryzensignite_aci_cc_card_type_icons_image"
            class="card-payments__upload"
            type="file"
            name="groups[tryzensignite][groups][aci_cc][fields][card_type_icons][value][images][]"
            accept="image/*"
            multiple
        />
        <span class="payments__upload-content"></span>
    </div>
    <div class="card-payments__images">
        <?php foreach ($existingData as $image): ?>
        <div class="card-payments__image">
            <img src="<?= $escaper->escapeHtmlAttr($image['image_full']) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Card Types')) ?>"
                 title="<?= $escaper->escapeHtmlAttr(__('Card Types')) ?>"
            />
            <input
                type="checkbox"
                class="delete_img"
                value="<?= $escaper->escapeHtmlAttr($image['image']) ?>"
                name="groups[tryzensignite][groups][aci_cc][fields][card_type_icons][value][delete][]"
            />
            <label><?= $escaper->escapeHtml(__('Delete')) ?></label>
        </div>
        <?php endforeach; ?>
    </div>
</div>
