<?php
use Aci\Payment\Block\Onepage\Success;

/**
 * @var Magento\Framework\Escaper $escaper
 * @var $block Success
 */
$additionalInfo = $block->getAdditionalInfo();


?>
<script type="text/x-magento-init">
    {
        "*": {
            "invalidateCart": {}
        }
    }
</script>
<div class="checkout-success">
    <?php if ($additionalInfo): ?>
        <p><b><?= $escaper->escapeHtmlAttr(__($additionalInfo)) ?></b></p>
    <?php endif; ?>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()):?>
            <p>
                <?=
                $escaper->escapeHtml(__(
                    'Your order number is: %1.',
                    sprintf(
                        '<a href="%s" class="order-number"><strong>%s</strong></a>',
                        $escaper->escapeUrl($block->getViewOrderUrl()),
                        $block->getOrderId()
                    )
                ), ['a', 'strong'])
                ?>
            </p>
        <?php  else:?>
            <p>
                <?= $escaper->escapeHtml(
                    __(
                        'Your order # is: <span>%1</span>.',
                        $block->getOrderId()
                    ),
                    ['span']
                ) ?>
            </p>
        <?php endif;?>
        <p>
            <?= $escaper->escapeHtml(__(
                'We\'ll email you an order confirmation with details and tracking info.'
            ))?>
        </p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
